[package]
name = "imoost"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
reqwest = { version = "0.12.12", features = ["json"] }
url = "2.5.4"
awc = "3.5.1"
openssl = "0.10.71"
hex = "0.4.3"
base64 = "0.22.1"